# /etc/haproxy/haproxy.cfg

global
    log 127.0.0.1:514 local0

defaults
	mode                	http
	log                 	global
	option              	httplog
	option              	dontlognull
	option forwardfor   	except 127.0.0.0/8
	option              	redispatch
	retries             	3
	timeout http-request	10s
	timeout queue       	1m
	timeout connect     	10s
	timeout client      	300s
	timeout server      	300s
	timeout http-keep-alive 10s
	timeout check       	10s
	maxconn             	20000

frontend openshift-api-server
	bind *:6443
	default_backend openshift-api-server
	mode tcp
	option tcplog

backend openshift-api-server
	balance source
	mode tcp
	server master1 10.64.1.101:6443 check
	server master2 10.64.1.102:6443 check
	server master3 10.64.1.103:6443 check
    
frontend machine-config-server
	bind *:22623
	default_backend machine-config-server
	mode tcp
	option tcplog

backend machine-config-server
	balance source
	mode tcp
	server master1 10.64.1.101:22623 check
	server master2 10.64.1.102:22623 check
	server master3 10.64.1.103:22623 check

frontend ingress-http
	bind *:80
	default_backend ingress-http
	mode tcp
	option tcplog

backend ingress-http
	balance source
	mode tcp
	server worker1 10.64.1.51:80 check
	server worker2 10.64.1.52:80 check
	server worker3 10.64.1.53:80 check
	server worker4 10.64.1.54:80 check
	server worker5 10.64.1.55:80 check

frontend ingress-https
	bind *:443
	default_backend ingress-https
	mode tcp
	option tcplog

backend ingress-https
	balance source
	mode tcp
	server worker1 10.64.1.51:443 check
	server worker2 10.64.1.52:443 check
	server worker3 10.64.1.53:443 check
	server worker4 10.64.1.54:443 check
	server worker5 10.64.1.55:443 check
